load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_DiagnosticManagement"
   ,  srcs       = ["aapFunctionalCluster_DiagnosticManagement.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_DiagnosticManagement_CancellationHandler.hpp"
         ,  "interface_DiagnosticManagement_Condition.hpp"
         ,  "interface_DiagnosticManagement_Conversation.hpp"
         ,  "interface_DiagnosticManagement_DTCInformation.hpp"
         ,  "interface_DiagnosticManagement_Event.hpp"
         ,  "interface_DiagnosticManagement_Indicator.hpp"
         ,  "interface_DiagnosticManagement_MetaInfo.hpp"
         ,  "interface_DiagnosticManagement_MultipleCondition.hpp"
         ,  "interface_DiagnosticManagement_MultipleEvent.hpp"
         ,  "interface_DiagnosticManagement_MultipleMonitor.hpp"
         ,  "interface_DiagnosticManagement_OperationCycle.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

